AddCSLuaFile()
return {Options = {
    AllowSprint = "Allow sprint",
    AvoidWalls = "Avoid walls",
    AvoidWalls_help = "If checked, the weapons try not to waste ink by hitting walls.",
    TransformOnCrouch = "Transform on crouch",
    TransformOnCrouch_help = "If checked, you will transform yourself on crouch.",
    CanDrown = "Enable drowning",
    CanHealInk = "Heal in ink",
    CanHealInk_help = "If checked, you can heal yourself when you're in ink.",
    CanHealStand = "Heal when standing",
    CanHealStand_help = "If checked, you can heal yourself gradually when you're out of ink.",
    CanReloadInk = "Reload in ink",
    CanReloadInk_help = "If checked, you can refill your ink tank when you're in ink.",
    CanReloadStand = "Reload when standing",
    CanReloadStand_help = "If checked, you can refill your ink tank gradually when you're out of ink.",
    DoomStyle = "DOOM-like",
    DoomStyle_help = "If checked, the view model will be placed at the center of the screen.",
    DrawCrosshair = "Draw crosshair",
    DrawInkOverlay = "Draw ink overlay",
    DrawInkOverlay_help = "If checked, a water effect will be drawn when you're in ink and first person mode.",
    Enabled = "Enable Splash SWEPs",
    ExplodeEveryone = "Explode everyone on kill",
    ExplodeEveryone_help = [[If checked, victims by the SWEPs will explode no matter what they have.
Otherwise, victims will only explode if they has the SWEPs.]],
    FF = "Enable friendly fire",
    Gain = {
        __printname = "Parameters",
        DamageScale = "Weapon damage multiplier [%]",
        HealSpeedInk = "Heal speed [%] (In ink)",
        HealSpeedStand = "Heal speed [%] (Out of ink)",
        MaxHealth = "Maximum health",
        InkAmount = "Amount of ink",
        ReloadSpeedInk = "Reload speed [%] (In ink)",
        ReloadSpeedStand = "Reload speed [%] (Out of ink)",
    },
    HideInk = "Hide ink in map",
    HideInk_help = "If checked, the whole ink in the map becomes invisible.",
    HurtOwner = "Explosion hurts its owner",
    InkColor = "Ink color",
    LeftHand = "Left hand mode",
    LeftHand_help = "If checked, the view model will be placed on the left.",
    MoveViewmodel = "Move viewmodel to avoid walls",
    MoveViewmodel_help = "When \"Avoid Walls\" is enabled, the view model will be animated.",
    NewStyleCrosshair = "Use alternative crosshair",
    NPCInkColor = {
        __printname = "NPC's ink color",
        Citizen = "Citizen",
        Combine = "Combine",
        Military = "Military",
        Zombie = "Zombie",
        Antlion = "Antlion",
        Alien = "Alien",
        Barnacle = "Barnacle",
        Others = "Others",
    },
    TakeFallDamage = "Enable fall damage",
    ToggleADS = "Toggle ADS instead of holding",
    ToggleADS_help = "Checked: Toggle ADS, Unchecked: Hold to ADS",
    TranslucentNearbyLocalPlayer = "Make local player translucent when nearby",
    TranslucentNearbyLocalPlayer_help = "If local player is too close to the camera, it will become translucent for clear vision.",
    weapon_splashsweps_shooter = {
    },
}}
