AddCSLuaFile()
local shooters = {
    mRepeatFrame = "f",
    mTripleShotSpan = "f",
    mInitVel = "du/f",
    mDegRandom = "deg",
    mDegJumpRandom = "deg",
    mSplashSplitNum = "num",
    mKnockBack = "du/f",
    mInkConsume = "ink",
    mInkRecoverStop = "f",
    mMoveSpeed = "du/f",
    mDamageMax = "hp",
    mDamageMin = "hp",
    mDamageMinFrame = "f",
    mStraightFrame = "f",
    mGuideCheckCollisionFrame = "f",
    mCreateSplashNum = "num",
    mCreateSplashLength = "du",
    mDrawRadius = "du",
    mColRadius = "du",
    mPaintNearDistance = "du",
    mPaintFarDistance = "du",
    mPaintNearRadius = "du",
    mPaintFarRadius = "du",
    mSplashDrawRadius = "du",
    mSplashColRadius = "du",
    mSplashPaintRadius = "du",
    mArmorTypeGachihokoDamageRate = "ratio",
    mDegBias = "ratio",
    mDegBiasKf = "ratio",
    mDegJumpBias = "ratio",
    mDegJumpBiasFrame = "f",
}
local t = {}
table.Merge(t, shooters)
return t
